sudo: false
language: java
jdk: oraclejdk11
notifications:
  slack:
    secure: ezbKqZ/R7e0TzEw3cbAkv1WA1vNTMYGy3ayh+edQy4boEeP1j90YKP7btzd9LJ0AM2PgCY6W/qz/TvPO0LFsMi564Pl/0D5MdshL5q11nZefbGSrMTesluKoNvAGMniX+sxNjPletiENFl81cWoiNA4kTuoVAphj/VnVOfMrDbq6olm68dfWOakjlt/QIkaR2BcZ/5DVWueeW6xRPs5oowqv9bg9zyJ9+NfFbMewIAGQ8hokvfaKumvGJKUbaysaxy1BmUs51VokcRh++JX1wJQ4EATvO7GXWxEsU0zI764iU0YDci9Ri3Tu0fvZf9kN96tK30rxkrsbV1DxSa6Ksg6jWx6xJiNqxZB/zJI2+O+s723Pz8m7tqjtBP4sin+lGf0TrVsDHAqfEi1quuZQwc103yT1b89rDgIpopgyqrD4WVQCL+tuPAVWWFQEJr+skZkdl9R3m1HObnUAUDRbsEdm7TeZYORllpuhPuE0cxgND6JVLcK5s71kCGq25ehZo7d319o40IR351WgS3EZDpkRGLkcjnAaAPDyJziDg31LlaQCII/BV4eAwERlEodN7f4GwAoa1ULG9z8+V+dHlBfvl1txDFxypiYzMrXUGX5hoJcQYm0h98YDtsbIgdxq2IzdlhO8PAE8M/vsvZiKTO/sfsgLP89dpQLHKJg+TwQ=
    on_success: always  # default: change: send a notification when the build status changes.
    on_failure: always  # default: always: always send a notification.